#!/bin/bash

# quick and dirty script to implement https://wiki.archlinux.org/title/Lenovo_IdeaPad_Gaming_3

function write_profile {
    # Make an acpi call
    echo '\_SB.PCI0.LPC0.EC0.SPMO' > /proc/acpi/call

    # read data
    echo $(tr -d '\0' < /proc/acpi/call) > /tmp/lenovo_power_mode
}

# maybe theres a better way to do this
write_profile
acpi_listen | while read -r line; do
    # if Fn + Q is pressed
    if [[ $line == "D320289E-8FEA- 000000e7 00000000" ]]; then
        write_profile
    fi
done
